### PR TITLE
modulesync 2.11.0

### PR DESCRIPTION
**Pull request by baurmatt**
modulesync 2.8.0

### CODE REVIEW

**Comment by baurmatt** [comment]
If I get this right, the failing jobs are because sidekiq 6 got released which requires Ruby >= 2.5. This isn't provided by Puppet 5 AIO packages.

Not sure how we should fix this. I see the following options:
* Drop Puppet 5 support
* Make webhook require sidekiq < 6
* ?

**Comment by baurmatt** [comment]
Opened https://github.com/voxpupuli/puppet_webhook/issues/104 for this.

**Comment by bastelfreak** [comment]
the module was initially created with pdk, so I'm not sure if modulesyncing is a good idea.

**Comment by dhollinger** [comment]
Let's revisit modulesync at a later date, but for now leave it as a PDK module. The larger community needs to have a discussion around how to make our modules play well with both PDK-using devs and non-PDK using devs.

**Pull request closed without merging**
