### PR TITLE
clean up README.md

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by bjoernhaeuser — APPROVED** [review]
The puppet code in the example looks a bit unintended

**Comment by bastelfreak** [comment]
Why do you think it's unintended? that's the example from our acceptance tests.

**Comment by bjoernhaeuser** [comment]
I meant that some spaces are missing, at least between "class" and its name ;)

**Comment by bastelfreak** [comment]
ah yes. fixed it

**Review by bjoernhaeuser — APPROVED** [review]

**Review by mmerfort — APPROVED** [review]

**Pull request merged**
